[node]
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
wait_time_for_microblocks = 10000
use_test_genesis_chainstate = true

[[events_observer]]
endpoint = "stacks-blockchain-api:3700"
retry_count = 255
events_keys = ["*"]

[burnchain]
chain = "bitcoin"
mode = "mocknet"
commit_anchor_block_within = 5000

[[ustx_balance]]
# "mnemonic": "point approve language letter cargo rough similar wrap focus edge polar task olympic tobacco cinnamon drop lawn boring sort trade senior screen tiger climb",
# "keyInfo": {
#   "privateKey": "753b7cc01a1a2e86221266a154af739463fce51219d97e4f856cd7200c3bd2a601",
#   "address": "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM",
#   "btcAddress": "mqVnk6NPRdhntvfm4hh9vvjiRkFDUuSYsH",
#   "index": 0
# }
address = "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM"
amount = 100000000000000

[[ustx_balance]]
# "mnemonic": "point approve language letter cargo rough similar wrap focus edge polar task olympic tobacco cinnamon drop lawn boring sort trade senior screen tiger climb",
# "keyInfo": {
#   "privateKey": "539e35c740079b79f931036651ad01f76d8fe1496dbd840ba9e62c7e7b355db001",
#   "address": "ST3EQ88S02BXXD0T5ZVT3KW947CRMQ1C6DMQY8H19",
#   "btcAddress": "n1htkoYKuLXzPbkn9avC2DJxt7X85qVNCK",
#   "index": 0
# }
address = "ST3EQ88S02BXXD0T5ZVT3KW947CRMQ1C6DMQY8H19"
amount = 100000000000000

[[ustx_balance]]
# "mnemonic": "laugh capital express view pull vehicle cluster embark service clerk roast glance lumber glove purity project layer lyrics limb junior reduce apple method pear",
# "keyInfo": {
#   "privateKey": "075754fb099a55e351fe87c68a73951836343865cd52c78ae4c0f6f48e234f3601",
#   "address": "ST3KCNDSWZSFZCC6BE4VA9AXWXC9KEB16FBTRK36T",
#   "btcAddress": "n2ZGZ7Zau2Ca8CLHGh11YRnLw93b4ufsDR",
#   "index": 0
# }
address = "ST3KCNDSWZSFZCC6BE4VA9AXWXC9KEB16FBTRK36T"
amount = 100000000000000

[[ustx_balance]]
#   "mnemonic": "level garlic bean design maximum inhale daring alert case worry gift frequent floor utility crowd twenty burger place time fashion slow produce column prepare",
#   "keyInfo": {
#     "privateKey": "374b6734eaff979818c5f1367331c685459b03b1a2053310906d1408dc928a0001",
#     "address": "STB2BWB0K5XZGS3FXVTG3TKS46CQVV66NAK3YVN8",
#     "btcAddress": "mhY4cbHAFoXNYvXdt82yobvVuvR6PHeghf",
#     "index": 0
#   }
address = "STB2BWB0K5XZGS3FXVTG3TKS46CQVV66NAK3YVN8"
amount = 100000000000000

[[ustx_balance]]
# "mnemonic": "drop guess similar uphold alarm remove fossil riot leaf badge lobster ability mesh parent lawn today student olympic model assault syrup end scorpion lab",
# "keyInfo": {
#   "privateKey": "26f235698d02803955b7418842affbee600fc308936a7ca48bf5778d1ceef9df01",
#   "address": "STSTW15D618BSZQB85R058DS46THH86YQQY6XCB7",
#   "btcAddress": "mkEDDqbELrKYGUmUbTAyQnmBAEz4V1MAro",
#   "index": 0
# }
address = "STSTW15D618BSZQB85R058DS46THH86YQQY6XCB7"
amount = 100000000000000

[connection_options]
read_only_call_limit_write_length = 0
read_only_call_limit_read_length = 100000
read_only_call_limit_write_count = 0
read_only_call_limit_read_count = 30
read_only_call_limit_runtime = 1000000000