[project]
name = "arkadiko-automate"
authors = ["Arkadiko Team"]
description = "Arkadiko Automate implements smart contract automation that can be run through a network of off-chain keepers"
telemetry = false
cache_dir = "/Users/philip/.clarinet/cache"
boot_contracts = ["pox", "costs-v2"]

[[project.requirements]]
contract_id = "SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR.arkadiko-token"

[contracts.arkadiko-automation-trait-v1]
path = "contracts/arkadiko-automation-trait-v1.clar"

[contracts.arkadiko-job-cost-calculation-trait-v1]
path = "contracts/arkadiko-job-cost-calculation-trait-v1.clar"

[contracts.arkadiko-job-cost-calculation-v1-1]
path = "contracts/arkadiko-job-cost-calculation-v1-1.clar"

[contracts.arkadiko-job-registry-trait-v1]
path = "contracts/arkadiko-job-registry-trait-v1.clar"

[contracts.arkadiko-job-registry-v1-1]
path = "contracts/arkadiko-job-registry-v1-1.clar"

[contracts.job-harvest-alex]
path = "contracts/job-harvest-alex.clar"

## Arkadiko DAO
[contracts.arkadiko-dao-token-trait-v1]
path = "contracts/arkadiko/arkadiko-dao-token-trait-v1.clar"

[contracts.arkadiko-token]
path = "contracts/arkadiko/arkadiko-token.clar"


[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
